# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploadtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='fileway',
            field=models.FileField(upload_to='upload/%Y%m%d'),
        ),
    ]
