# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170830_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileway',
            field=models.FileField(storage=models.CharField(max_length=30), upload_to='web/hey/Heygears/Excel'),
        ),
    ]
