# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170831_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileway',
            field=models.FileField(upload_to='web/hey/Heygears/Excel/%Y%m%d%H%M%S'),
        ),
    ]
